In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
dataset = pd.read_csv(r'C:\Users\HP\Desktop\data_to_use.csv')

In [3]:
dataset.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [4]:
dataset.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [14]:
new_set =dataset[['Duration', 'Date', 'Pulse', 'Maxpulse']]

In [39]:
new_set

    Duration          Date  Pulse  Maxpulse
0         60  '2020/12/01'    110       130
1         60  '2020/12/02'    117       145
2         60  '2020/12/03'    103       135
3         45  '2020/12/04'    109       175
4         45  '2020/12/05'    117       148
5         60  '2020/12/06'    102       127
6         60  '2020/12/07'    110       136
7        450  '2020/12/08'    104       134
8         30  '2020/12/09'    109       133
9         60  '2020/12/10'     98       124
10        60  '2020/12/11'    103       147
11        60  '2020/12/12'    100       120
12        60  '2020/12/12'    100       120
13        60  '2020/12/13'    106       128
14        60  '2020/12/14'    104       132
15        60  '2020/12/15'     98       123
16        60  '2020/12/16'     98       120
17        60  '2020/12/17'    100       120
18        45  '2020/12/18'     90       112
19        60  '2020/12/19'    103       123
20        45  '2020/12/20'     97       125
21        60   2020/12/21'    108       131
22        45    2020/12/22    100       119
23        60  '2020/12/23'    130       101
24        45  '2020/12/24'    105       132
25        60  '2020/12/25'    102       126
26        60      20201226    100       120
27        60  '2020/12/27'     92       118
28        60  '2020/12/28'    103       132
29        60  '2020/12/29'    100       132
30        60  '2020/12/30'    102       129
31        60  '2020/12/31'     92       115

In [36]:
new_set['Date'].dropna()

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
12    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21     2020/12/21'
22      2020/12/22
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26        20201226
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: object

In [37]:
new_set

    Duration          Date  Pulse  Maxpulse
0         60  '2020/12/01'    110       130
1         60  '2020/12/02'    117       145
2         60  '2020/12/03'    103       135
3         45  '2020/12/04'    109       175
4         45  '2020/12/05'    117       148
5         60  '2020/12/06'    102       127
6         60  '2020/12/07'    110       136
7        450  '2020/12/08'    104       134
8         30  '2020/12/09'    109       133
9         60  '2020/12/10'     98       124
10        60  '2020/12/11'    103       147
11        60  '2020/12/12'    100       120
12        60  '2020/12/12'    100       120
13        60  '2020/12/13'    106       128
14        60  '2020/12/14'    104       132
15        60  '2020/12/15'     98       123
16        60  '2020/12/16'     98       120
17        60  '2020/12/17'    100       120
18        45  '2020/12/18'     90       112
19        60  '2020/12/19'    103       123
20        45  '2020/12/20'     97       125
21        60   2020/12/21'    108       131
22        45    2020/12/22    100       119
23        60  '2020/12/23'    130       101
24        45  '2020/12/24'    105       132
25        60  '2020/12/25'    102       126
26        60      20201226    100       120
27        60  '2020/12/27'     92       118
28        60  '2020/12/28'    103       132
29        60  '2020/12/29'    100       132
30        60  '2020/12/30'    102       129
31        60  '2020/12/31'     92       115

In [34]:
new_set['Duration'].replace({'450': '45'}, inplace =True )

C:\Users\HP\AppData\Local\Temp\ipykernel_25688\2130094402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_set['Duration'].replace({'450': '45'}, inplace =True )

In [35]:
new_set

    Duration          Date  Pulse  Maxpulse
0         60  '2020/12/01'    110       130
1         60  '2020/12/02'    117       145
2         60  '2020/12/03'    103       135
3         45  '2020/12/04'    109       175
4         45  '2020/12/05'    117       148
5         60  '2020/12/06'    102       127
6         60  '2020/12/07'    110       136
7        450  '2020/12/08'    104       134
8         30  '2020/12/09'    109       133
9         60  '2020/12/10'     98       124
10        60  '2020/12/11'    103       147
11        60  '2020/12/12'    100       120
12        60  '2020/12/12'    100       120
13        60  '2020/12/13'    106       128
14        60  '2020/12/14'    104       132
15        60  '2020/12/15'     98       123
16        60  '2020/12/16'     98       120
17        60  '2020/12/17'    100       120
18        45  '2020/12/18'     90       112
19        60  '2020/12/19'    103       123
20        45  '2020/12/20'     97       125
21        60   2020/12/21'    108       131
22        45    2020/12/22    100       119
23        60  '2020/12/23'    130       101
24        45  '2020/12/24'    105       132
25        60  '2020/12/25'    102       126
26        60      20201226    100       120
27        60  '2020/12/27'     92       118
28        60  '2020/12/28'    103       132
29        60  '2020/12/29'    100       132
30        60  '2020/12/30'    102       129
31        60  '2020/12/31'     92       115